# Generated by Django 4.2.4 on 2023-10-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calories_burned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
