"""Add chef_id not null

Revision ID: 51c790c231c1
Revises: 85af59eca911
Create Date: 2023-11-16 16:05:44.526194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c790c231c1'
down_revision: Union[str, None] = '85af59eca911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'chef_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'chef_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
