# Generated by Django 4.2.4 on 2023-10-23 07:31

from django.db import migrations, models


def create_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoe')
    unique_brands = apps.get_model('main_app', 'UniqueBrands')
    db_alias = schema_editor.connection.alias
    unique_brands_names = shoe.objects.values_list('brand', flat=True).distinct()
    for brand_name in unique_brands_names:
        unique_brands.objects.using(db_alias).create(brand_name=brand_name)

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# main_app.migrations.0003_migrate_unique_brands

class Migration(migrations.Migration):

    replaces = [('main_app', '0001_initial'), ('main_app', '0002_uniquebrands'), ('main_app', '0003_migrate_unique_brands')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniqueBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RunPython(
            code=create_unique_brands,
        ),
    ]
